dist: trusty
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: pWhsthzcP9qps05g+zgFaUFnheTRFWDEjVbIXxnpPDZLHR7akBjlfW6LbJTtLw7An0XlxFrWdXQUYDsvHVst38JHpUTfq8+9TTuMcvsUrR66KHxwsYjl60eQhb+nRePJEc+hsZs32vmOC/JoVflqgiLWzKNAUDCNo3uzcqEHWbADHniWBv5AmxJzI+nZj92rPujmhfOldSuCX7MIB1M3ODFppYaSBVtpIYZePM/9SN+N469XJaPrcc1+zAS/wUfSCyjVwIGUoVatp+v4wOOEhQJR6tSMO2wAbfVOayfgrxoKz0MqAUe4+7h+/dt5MAHkOe8GzrfRcYkFeQaD1vVX+YXBZQbGsvJ9qGZd1U5GuIwuWrJRFgKaKu0GAOTkZ+VYUprCWjsivrbJXJFysZTzE5OGaRT335L+f+KPYj6n1eD49SGo7yJewJ3eDUhz6ElS6BJyaAvuHv9PnUNJVfAtbDR4FQEt9LjXouNkrgesWQguevGyIGyo2rBkX8GDvCGNeIay/u4syJwJYUuwNYjvav04Ihzn9XEZxgtppa71mP0Q3D+qNiwqw0KjuLiPVWFVDk52EvYl0V1ZgAofi4uMR5+OS7uq5CIFh7CwIrQtCsCbfAnmtm2VYOc1XsSmD2xvzejfrRGsKD9tgDFnE6fJWQA//XjipP2JWHyaof2k3LM=
language: python
python:
- '3.6'
before_install:
- pip install --upgrade pytest
install:
- pip install .[test]
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=validate_version_code --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- sonar-scanner
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: SsiuqekOri/ahtwDchpeKZ8pIA1p5fR3m/2nrirRJfb8XBoIjr2fA3UmfJZKfZcwL+MAO2iCfYKC8zPB6uQouRvqjkkTB2WZ/epBD5Cae2OJjwiJiigbkuLCoAX5YXPcF74vXnjOhva60vby5duL8qyocPAzaU/nR489LP4lQGtP8uObg5+K9ZU+WMyaEm97UC9pJMfwGKhkF0RUQ0hdssletCKYvQj+khEZS3ATjSJsHVsFlohws0zKtX0Y+8zd8jvbYb5zI5ZjPPpnrXypcs2ovXR0tA9SVqLIefde7J1GJ7sHnU5bJVFtYcR0/7CpKkBvD4CeYeQLhqAVSsM+E5nTrxPrbbUNaAg5WlPAeHsn/Xwn+hiFdlxNYbttLRUy5F8kTbCFcN3YWDImcufauEa3U20/s0Cue9zSDzzKscvUIkHuDTxHDlX/Hjv01UsJzPowH9hitpDgsxvhPGfNbs2tVSgvNEPXEZoFi/LRGLx77Jsj9niFda4mgkq67O1xNKlpQUpAMspdQ1fBcXyx6c8ETpnWTytWap/EdDklDfb4Y0Gcydjq+5AwMnDIoes79GAe1bfMF26iy9vloU5x6lmbQOf+sct7RsdogecQ30rlKHBurwT3/sZWsFhCXdcl37Dj2FeZGRutm38hMaQr/7t3dVKbOerP2AmIsbKwOMM=
  - secure: IsbvIzHwYAAKdz4gru1NCXNtOj1Qvu7BvS/dmEOVbaCwizTEZjnqxp2/qrR60MBxzY5Z2fjV6gXqIOi8yQUfhf369nr5X7jgGU8NfYkQ+Kn+NSNDnZ7NZ8QXmBviIABlczjVi0xNBkbBCy1J8uHK2RK9ijDVIoHwRySkFvOjrJblv1fOMrkT9SvwOzmginxHNfkpwpW6Edl2qIqvoJkMxdTRRDGfbFaRu7urgq5YpIVCRuHOWY3bV0cgXedZava/yfwt8OJKjLZm7ab1cCounn59dSLMMDwBSwdPRd0z3WsIp5ARhspvz4et66g8L/datYzfls9prYOf5fzx4WnvP1vinQrftKolyB32kCO52wXT6MF5sXe92HL9TAJjZiwAauGZvbOw7ggoFC8/R5TNtHpnruEA7hA4kJyPbTLU9pFaqiH0F/VwC4mJa91u6WXr9I4yrafUGNWWfc6Ji/g5L7EYm66TLHqi+fpAO4TpxgStBVCuBF6TEM6RkgFUwn2//c2JRwM6EThuklb44xT+CosEXqe2V0dPFg9iejXsTyRBB9CR1zRH6WcCLAw3jaWqM/uOlxrWoha8AaBq4QFWVJAOHugL+i5Ar3ZmgWhQ0RpSMLD2aVeBLSpnzbXHL3MohyVEjfDB4d+yfQ4eheEC55hx65GYK9zX/Nkz6o5a8Ks=
